[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "OceanSim"
description = "Underwater simulation utilities"
authors = ["NVIDIA", "FRoG--University of Michigan"]
repository = ""
keywords = ["Underwater","Sensor","Scene"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}

[[python.module]]
name = "OceanSim.more_python"

[[python.module]]
name = "OceanSim.DVL_python"

[[python.module]]
name = "OceanSim.PhysXraycast_python"

[[python.module]]
name = "OceanSim.ImagingSonar_python"

[[python.module]]
name = "OceanSim.fossen_python"